### ISSUE TITLE
Software OpenCL

### ISSUE THREAD

**Issue by jdluzen** [GPUOpen-LibrariesAndSDKs/RadeonImageFilter#10]
Thanks for this great project! I've already been playing with it and seeing what its capabilities are, and where I can use it.

I have a 5700XT which is currently used when I am developing with this library. The main goal of mine is to see if it can reach more platforms. To that end, I've been attempting to run it strictly under OpenCL, more specifically, software implementations of OpenCL. So far I've tried 2 different ones, and both have immediately produced errors. Is some form of hardware acceleration required? Is there any way I can run this library on CPU only?

**Comment by bsavery** [comment]
Hi there.  Can you give more details of what you're doing?  

The example here: https://radeon-pro.github.io/RadeonProRenderDocs/en/rif/basic_example.html
Is pretty good.  When you create the rif context you specify the backend type and device.  RIF_BACKEND_API_OPENCL is probably what you want and most likely device 0 but this could depend on your setup.  There is no specific hardware acceleration needed.

**Comment by BenjaminCoquelle** [comment]
AMD doesn't support OpenCL CPU anymore.
If you have an intel CPU and the OpenCL driver from intel CPU you can use our OpenCL interop mechanism to target the intel CPU
