### ISSUE TITLE
AI upscale filter fail with gfx803 + MIOpen 2.0.5 

### ISSUE THREAD

**Issue by Umio-Yasuno** [GPUOpen-LibrariesAndSDKs/RadeonImageFilter#13]
AI upscale filter fail for error of MIOpen when use Fast model.

```
[MSG  @RIF]: Loaded RIF API version: 1.7.0.0xbbcfd912
INFO: MIOpen version: 2.0.5
[MSG  @RIF]: Loading model: ../RadeonImageFilter/models//upscale2x_fast.pb
INFO: Memory: required: 66355200, single node max: 58982400, requested sum: 239616000
MIOpen Error: /home/admin/JN/WS/MIOpen_Build/src/ocl/convolutionocl.cpp:1017: Fwd Convolution cannot be executed due to incorrect params
ERROR: Graph/MemNet/MemBlock_1/ResBlock_1/Conv1/Conv2D:Conv2d: miopenFindConvolutionForwardAlgorithm failed, status: miopenStatusUnknownError (7)
[ERROR@RIF]: rmlPrepareModel failed: Graph/MemNet/MemBlock_1/ResBlock_1/Conv1/Conv2D:Conv2d: miopenFindConvolutionForwardAlgorithm failed, status: miopenStatusUnknownError (7) at file /home/admin/JN/WS/RadeonProImageProcessor_Build/src/RadeonImageFilters.cpp line 1220
```
Also Good and Best model failed, but so VRAM of 4GB may was not enough.

OS: Debian GNU/Linux bullseye/sid
CPU: Ryzen 5 2600
GPU: Radeon RX 560 4GB (Polaris11, gfx803)
OpenCL: OpenCL 2.0 AMD-APP (3212.0)

### Log

`$ MIOPEN_LOG_LEVEL=7 ./rif-cmd -i ../input/sample.png -o ../output/debug.png -f ai_upscale "3,../RadeonImageFilter/models/"`
(1: Good, 2: Best, 3: Fast)

[fast_model.log](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/files/6175019/fast_model.log)
[fast_model_rif-trace-1616223509-1.7.0.0xbbcfd912.tar.gz](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/files/6175033/fast_model_rif-trace-1616223509-1.7.0.0xbbcfd912.tar.gz)

[good_model.log](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/files/6175040/good_model.log)
[good_model_rif-trace-1616224368-1.7.0.0xbbcfd912.tar.gz](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/files/6175041/good_model_rif-trace-1616224368-1.7.0.0xbbcfd912.tar.gz)

[best_model.log](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/files/6175038/best_model.log)
[best_model_rif-trace-1616224280-1.7.0.0xbbcfd912.tar.gz](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/files/6175039/best_model_rif-trace-1616224280-1.7.0.0xbbcfd912.tar.gz)

**Comment by stmuxa** [comment]
Hey @Umio-Yasuno 
Could you please try updated version? Make sure you replace files in `models/kernels` directory.
https://drive.google.com/file/d/1i0MLLN2pY5DPcHcz-TwDDEvO3JhHdmGq/view?usp=sharing

**Comment by Umio-Yasuno** [comment]
Thanks @stmuxa 
However, the result was the same. The log did not change either.

Also, `rifContextGetInfo(context, RIF_CONTEXT_KERNELS_SOURCE_DIR, sizeof(kernel_src),   &kernel_src,   &ret);` returned "`/home/admin/JN/WS/RadeonProImageProcessor_Build/src/kernels/opencl/`" , 
Is this result correct?

```
   char kernel_src[256], kernel_cache[256];
   size_t ret;
   rifContextGetInfo(context, RIF_CONTEXT_KERNELS_SOURCE_DIR, sizeof(kernel_src),   &kernel_src,   &ret);
   rifContextGetInfo(context, RIF_CONTEXT_KERNELS_CACHE_DIR,  sizeof(kernel_cache), &kernel_cache, &ret);
   printf("Kernel Source Dir: %s\n", kernel_src);
   printf("Kernel Cache  Dir: %s\n", kernel_cache);

```

```
Backend API: 	 OpenCL
Vendor: 	 Advanced Micro Devices, Inc.
Device Name: 	 Baffin [Radeon RX 550 640SP / RX 560/560X]

[MSG  @RIF]: Loaded RIF API version: 1.7.0.0xbbcfd912
INFO: MIOpen version: 2.0.5
Kernel Source Dir: /home/admin/JN/WS/RadeonProImageProcessor_Build/src/kernels/opencl/
Kernel Cache  Dir: kernelsCache
Execute
[MSG  @RIF]: Loading model: ../../new-miopen/radeonimagefilters-move-miopen-to-2.10.0-linux-4171ca-Ubuntu18-dynamic/models/upscale2x_fast.pb
INFO: Memory: required: 66355200, single node max: 58982400, requested sum: 239616000
MIOpen Error: /home/admin/JN/WS/MIOpen_Build/src/ocl/convolutionocl.cpp:1017: Fwd Convolution cannot be executed due to incorrect params
ERROR: Graph/MemNet/MemBlock_1/ResBlock_1/Conv1/Conv2D:Conv2d: miopenFindConvolutionForwardAlgorithm failed, status: miopenStatusUnknownError (7)
[ERROR@RIF]: rmlPrepareModel failed: Graph/MemNet/MemBlock_1/ResBlock_1/Conv1/Conv2D:Conv2d: miopenFindConvolutionForwardAlgorithm failed, status: miopenStatusUnknownError (7) at file /home/admin/JN/WS/RadeonProImageProcessor_Build/src/RadeonImageFilters.cpp line 1220
```

**Comment by givinar** [comment]
Hi @Umio-Yasuno
We found the reasone of issue.
It'll be fixed in the next version of RIF.
Thanks.

**Comment by Umio-Yasuno** [comment]
I tried v1.7.1 (Ubuntu18-Clang and Ubuntu20), but that failed.

OS: Debian GNU/Linux 11 (bullseye)
CPU: Ryzen 5 2600

GPU: Radeon RX 560 4GB (Polaris11, gfx803)
OpenCL: OpenCL 2.0 AMD-APP (3275.0)

[fast_model.log](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/files/6610023/fast_model.log)
[rif-trace-1623078002-1.7.1.0xfe53c43a.tar.gz](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/files/6610055/rif-trace-1623078002-1.7.1.0xfe53c43a.tar.gz)

**Comment by givinar** [comment]
Hi @Umio-Yasuno,
Could you send libMIOpen, libRadeonML and  libRadeonML_MIOpen.

**Comment by Umio-Yasuno** [comment]
I am using RadeoImageFilter as a submodule and setting `LD_LIBRARY_PATH="${HOME}/github/rif-cmd/RadeonImageFilter/Ubuntu18-Clang/Dynamic/":$LD_LIBRARY_PATH` for `.bashrc`.
<https://github.com/Umio-Yasuno/rif-cmd>

Is there a problem with my `CMakeLists.txt`?
<https://github.com/Umio-Yasuno/rif-cmd/blob/main/CMakeLists.txt>

I checked with `tree` command, and the soft link seems to be correct.
```
RadeonImageFilter/Ubuntu18-Clang/
└── Dynamic
    ├── libMIOpen.so -> libMIOpen.so.2
    ├── libMIOpen.so.2 -> libMIOpen.so.2.0.5
    ├── libMIOpen.so.2.0.5
    ├── libOpenImageDenoise.so -> libOpenImageDenoise.so.0
    ├── libOpenImageDenoise.so.0 -> libOpenImageDenoise.so.0.9.0
    ├── libOpenImageDenoise.so.0.9.0
    ├── libRadeonImageFilters.so -> libRadeonImageFilters.so.1
    ├── libRadeonImageFilters.so.1 -> libRadeonImageFilters.so.1.7.1
    ├── libRadeonImageFilters.so.1.7.1
    ├── libRadeonML_MIOpen.so -> libRadeonML_MIOpen.so.0
    ├── libRadeonML_MIOpen.so.0 -> libRadeonML_MIOpen.so.0.9.12
    ├── libRadeonML_MIOpen.so.0.9.12
    ├── libRadeonML.so -> libRadeonML.so.0
    ├── libRadeonML.so.0 -> libRadeonML.so.0.9.12
    └── libRadeonML.so.0.9.12
RadeonImageFilter/Ubuntu20/
└── Dynamic
    ├── libMIOpen.so -> libMIOpen.so.2
    ├── libMIOpen.so.2 -> libMIOpen.so.2.0.5
    ├── libMIOpen.so.2.0.5
    ├── libOpenImageDenoise.so -> libOpenImageDenoise.so.0
    ├── libOpenImageDenoise.so.0 -> libOpenImageDenoise.so.0.9.0
    ├── libOpenImageDenoise.so.0.9.0
    ├── libRadeonImageFilters.so -> libRadeonImageFilters.so.1
    ├── libRadeonImageFilters.so.1 -> libRadeonImageFilters.so.1.7.1
    ├── libRadeonImageFilters.so.1.7.1
    ├── libRadeonML_MIOpen.so -> libRadeonML_MIOpen.so.0
    ├── libRadeonML_MIOpen.so.0 -> libRadeonML_MIOpen.so.0.9.12
    ├── libRadeonML_MIOpen.so.0.9.12
    ├── libRadeonML.so -> libRadeonML.so.0
    ├── libRadeonML.so.0 -> libRadeonML.so.0.9.12
    └── libRadeonML.so.0.9.12

2 directories, 30 files

```

**Comment by givinar** [comment]
Thanks @Umio-Yasuno 
I checked on my side, everything works fine. But I saw this line in your log - MIOpen(OpenCL): Info [DetectAmdRocmMetadataVersion] ROCm MD version AMDHSA_1_0, MIOpen version 2.0.5.2d225393-dirty
What driver are you using? The RIF shouldn't work on ROCm, use amdgpu pro instead. It can be the reason .

**Comment by BenjaminCoquelle** [comment]
We don't support ROCm, only amdgpu-pro stack
That's why we ship a custom version of miopen here that can run on amdgpu-pro
I will actually close that issue as it is on a non supported system

**Comment by Umio-Yasuno** [comment]
Do you have any plans to support it in the ROCm OpenCL Driver in the future?

**Comment by BenjaminCoquelle** [comment]
No we don't as the main goal of the library is to provide support for amdgpu-pro stack on linux.
The lib is mainly aimed to be integrated onto graphics based application and ROCm is not designed for that

**Comment by Umio-Yasuno** [comment]
I understand.
Thank you for your support!
@BenjaminCoquelle @givinar @stmuxa
