### ISSUE TITLE
Invalid API version in v1.7.2 header files

### ISSUE THREAD

**Issue by pmavridis** [GPUOpen-LibrariesAndSDKs/RadeonImageFilter#19]
After updating to v1.7.2, rifCreateContext returns RIF_ERROR_INVALID_API_VERSION.  (v1.7.0 works without any errors).

I think it's related to the version in RadeonImageFilters_version.h, which reads:
```
#define RIF_VERSION_MAJOR      1
#define RIF_VERSION_MINOR      7
#define RIF_VERSION_REVISION   1
#define RIF_COMMIT_INFO        0xfdc139ba
```

I have tried changing the revision to 2 (since this is for the 1.7.2 binaries), but I still get an error, probably because the commit hash is not correct.

**Comment by givinar** [comment]
Hi @pmavridis 
Thank you. We'll fix that.

**Comment by givinar** [comment]
Hi @pmavridis 
The problem has been fixed in version 1.7.3.
Could you close the issue?

**Comment by pmavridis** [comment]
Hi! Where can I find the 1.7.3 release to test in our code? 
Right now the latest tag on the public repository is 1.7.2 and the last version in the releases page (https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/releases) is also 1.7.2.

**Comment by BenjaminCoquelle** [comment]
The release has ben published now.
It was just in the git repo before

**Comment by pmavridis** [comment]
Thanks a lot, the new version works as expected.
