### ISSUE TITLE
CMake error on "copy_dependencies" when building samples

### ISSUE THREAD

**Issue by FlakPacket** [GPUOpen-LibrariesAndSDKs/RadeonImageFilter#2]
When I try to build the sample programs with CMake on Ubuntu 18.04, I get this error message:

```
CMake Error at MLAA/CMakeLists.txt:16 (copy_dependencies):
  Unknown CMake command "copy_dependencies".
```

Where is `copy_dependencies` supposed to be defined?

**Comment by BenjaminCoquelle** [comment]
Hi, we just fixed the cmake, can you give it a try. It was using our internal mechanism.

**Comment by FlakPacket** [comment]
Thanks, that solved the problem, the sample programs build cleanly now!
