### ISSUE TITLE
Depth of field effect not working with RPR generated images (color/depth)

### ISSUE THREAD

**Issue by marceloroca** [GPUOpen-LibrariesAndSDKs/RadeonImageFilter#3]
I've generated color and depth images with RPR , and using the RIF_IMAGE_FILTER_DEPTH_OF_FIELD filter, but the result image is the same that the source.

this is the code:

```
//Create image filter
status = rifContextCreateImageFilter(context, RIF_IMAGE_FILTER_DEPTH_OF_FIELD, &filter);
if (status != RIF_SUCCESS)
{
	return -1;
}

// Load input image
inputImage = ImageTools::LoadImage("images/22.png", context);
inputImageDepth = ImageTools::LoadImage("images/22_Depth.png", context);

if (!(inputImage && inputImageDepth))
{
	return -1;
}

//Create output image
rif_image_desc desc;
size_t retSize;
rifImageGetInfo(inputImage, RIF_IMAGE_DESC, sizeof(desc), &desc, &retSize);
status = rifContextCreateImage(context, &desc, nullptr, &outputImage);
if (status != RIF_SUCCESS)
{
	return -1;
}

//Attach filter and set parameters
if (rifImageFilterSetParameter1u(filter, "kernelSize", RIF_DEPTH_OF_FIELD_FILTER_KERNEL_SIZE_LARGE) != RIF_SUCCESS) { return -1; }
if (rifImageFilterSetParameter1f(filter, "focusD", 1.8f) != RIF_SUCCESS) { return -1; }
if (rifImageFilterSetParameter1f(filter, "aperture", 0.8f) != RIF_SUCCESS) { return -1; }
if (rifImageFilterSetParameterImage(filter, "depthImg", inputImageDepth) != RIF_SUCCESS) { return -1; }
if (rifCommandQueueAttachImageFilter(queue, filter, inputImage, outputImage) != RIF_SUCCESS) { return -1; }

//Execute queue
if (rifContextExecuteCommandQueue(context, queue, nullptr, nullptr, nullptr) != RIF_SUCCESS) { return -1; }

//Save output image
ImageTools::SaveImage(outputImage, "22_final.png");
```

the depth image is generated with RPR with this code:

```
rpr_framebuffer frame_buffer_depth, frame_buffer_depth2;
CHECK(rprContextCreateFrameBuffer(context, fmt, &desc, &frame_buffer_depth));
CHECK(rprContextCreateFrameBuffer(context, fmt, &desc, &frame_buffer_depth2));
CHECK(rprFrameBufferClear(frame_buffer_depth));
CHECK(rprFrameBufferClear(frame_buffer_depth2));
CHECK(rprContextSetAOV(context, RPR_AOV_DEPTH, frame_buffer_depth));

// Progressively render an image

CHECK(rprContextResolveFrameBuffer(context, frame_buffer_depth, frame_buffer_depth2, true));
CHECK(rprFrameBufferSaveToFile(frame_buffer_depth2, "22_depth.png"));
```

The depth image has pixel values between 1 and 10000.

RPR SDK version: 0x00103503 build: 0x92f604e2
RIF SDK version:  1.5.3 commit: 0x47b72111
OS: Windows 10 
GPU: Radeon RX 5500 XT
Driver: 20.5.1

**Comment by stmuxa** [comment]
Can you share the generated images as well?

**Comment by marceloroca** [comment]
I've changed to "exr", but I have the same problem, and others problems:

- If I export the RPR_AOV_COLOR to "exr" file, the image is completely different than a "png" file
- If put values lower than 1 in "focusD" all the image is out of focus, but for 1 and over all the image is on focus

I'm  sharing the generated images, the RPR program to generate the images and the RIF program to apply the filter

[dof test.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/files/4960970/dof.test.zip)

RPR program is a modified of SDK tutorial 22_material_uber
RIF program is a modified from Bloom filter

**Comment by stmuxa** [comment]
@marceloroca can you also collect trace files accodring to this manual https://radeon-pro.github.io/RadeonProRenderDocs/en/rif/tracing.html
archive them and attach.
Thanks.

**Comment by marceloroca** [comment]
Here is, 
[rif_trace_1595437696.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/files/4961398/rif_trace_1595437696.zip)

**Comment by stmuxa** [comment]
So, the gray cubes are at about 19-21 meters from camera
I set:
```
rifImageFilterSetParameter1f(filter, "focusD", 20);
```
I also changed focal length parameter to 100 (https://radeon-pro.github.io/RadeonProRenderDocs/en/rif/filters/depth_of_field.html)
```
rifImageFilterSetParameter1f(filter, "focalL", 100);
```
and got the images blurred.


![image](https://user-images.githubusercontent.com/10169674/88264423-63ef9480-ccd4-11ea-884a-c98fdcd48f79.png)

**Comment by marceloroca** [comment]
Hi, thank you for your help, that's working with that scene, but when I use the the same logic to another scene, the resulting image is completely blurred.

I have this scene: 

![image](https://user-images.githubusercontent.com/153597/88331490-0d498100-ccfb-11ea-952a-78a5c3ee7923.png)

and I'm using this parameters:

  FocusDistance = 12f,
  Aperture = .8f,
  FocalLenght = 100,

I want to focus on the table at 12 meters from the camera.

Here is the rif_trace

[rif_trace_1595537150.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/files/4968673/rif_trace_1595537150.zip)

the rpr trace is here: 
https://1drv.ms/u/s!AuSw-ga8WQGqhhOsT8tS8Pj5soFd?e=7veFI5

the images here:

[images.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/files/4968694/images.zip)

**Comment by marceloroca** [comment]
thanks for your help, it's working
