### ISSUE TITLE
RIF_IMAGE_FILTER_GAMMA_CORRECTION filter generates an RIF_ERROR_INVALID_FILTER_ARGUMENT_NAME error

### ISSUE THREAD

**Issue by marceloroca** [GPUOpen-LibrariesAndSDKs/RadeonImageFilter#4]
I'm trying to use the Gamma Correction (https://radeon-pro.github.io/RadeonProRenderDocs/en/rif/filters/gamma_correction.html)

```
status = rifContextCreateImageFilter(context, RIF_IMAGE_FILTER_GAMMA_CORRECTION, &filter);
...
status = rifImageFilterSetParameter1f(filter, "cGamma", 0.1f);
```

When setting the cGamma parameter the status return RIF_ERROR_INVALID_FILTER_ARGUMENT_NAME 

[rif_trace_1595451945.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/files/4962654/rif_trace_1595451945.zip)

RIF SDK version: 1.5.3 commit: 0x47b72111
OS: Windows 10
GPU: Radeon RX 5500 XT
Driver: 20.5.1

**Comment by BenjaminCoquelle** [comment]
it is a typo in the documentation on our side we will fix it
You need to use "gamma"
(rifImageFilterSetParameter1f(filter_, "gamma", gamma)

**Comment by marceloroca** [comment]
Thanks, is working now
