### ISSUE TITLE
Error wrong paramaters on RIF_IMAGE_FILTER_PHOTO_TONEMAP

### ISSUE THREAD

**Issue by marceloroca** [GPUOpen-LibrariesAndSDKs/RadeonImageFilter#5]
I'm trying to use the Photographic Tone Mapping Filter (https://radeon-pro.github.io/RadeonProRenderDocs/en/rif/filters/photographic_tone_mapper.html), but when I try to enter some parameters the library return with errors:

rifImageFilterSetParameter1f(imageFilter, "exposure", value); => RIF_ERROR_INVALID_FILTER_ARGUMENT_NAME
rifImageFilterSetParameter1f(imageFilter, "whitepoint", value) => RIF_ERROR_INVALID_PARAMETER_TYPE
rifImageFilterSetParameter1f(imageFilter, "ISO", value); ) => RIF_ERROR_INVALID_PARAMETER_TYPE

for "ISO" values works fine if I use rifImageFilterSetParameter1u (in the documentation say the parameter type is float)
for "whitepoint" the documentation says type rif_float, I'm using float but that nots work.

RIF version 1.5.3 commit 0x47b72111

thanks,

**Comment by BenjaminCoquelle** [comment]
Hi @marceloroca, thanks again for the feedback. It is again typo in the doc that we will fix tomorrow morning
In the meantime :
"exposure" is actually "exposureTime"
ISO is in uint
and whitepoint a float4

**Comment by marceloroca** [comment]
Thanks, is working now.
