### ISSUE TITLE
Dynamic Resampling filter outputs a broken image

### ISSUE THREAD

**Issue by Umio-Yasuno** [GPUOpen-LibrariesAndSDKs/RadeonImageFilter#9]
Hello.  
I tried Dynamic Resampling filter, but that always outputs a broken image.  

[rif-trace-1611169671-1.6.2.0xbdf2aac0.tar.gz](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonImageFilter/files/5844709/rif-trace-1611169671-1.6.2.0xbdf2aac0.tar.gz)

OS: Debian GNU/Linux bullseye/sid
CPU: Ryzen 5 2600
GPU: Radeon RX 560 4GB (Polaris11, gfx803)
OpenCL: OpenCL 2.0 AMD-APP (3212.0)

**Comment by givinar** [comment]
Hello. Thanks.
We found the problem. This will be fixed in the next version.

**Comment by Umio-Yasuno** [comment]
Thanks for your reply and validation.  
I will wait for the next version.

**Comment by Umio-Yasuno** [comment]
I have confirmed the fix in v1.7.0 .
Thank you.
